torch_seed: 101 #set torch seed
verbose: True
model_settings:
  num_channels: 3 #number of input channels (3 for RGB)
  num_classes: 4 #number of segmentation classes excluding background
  bilinear: False
  model_out_path: ./ #where to save model 
train_settings:
  epochs: 1 #num epochs to train for 
  batch_size: 7 
  val_percent: 0.1 #percent of training set to reserve as validation set 
  save_checkpoint: True #whether or not to save checkpoints
  save_checkpoint_freq: 50 #save model every ___ epochs
  dir_checkpoint: './checkpoints/' #directory to save checkpoint models to 
  learning_rate: 1e-5 
  amp: False
  weight_decay: 1e-8
  momentum: 0.999
  gradient_clipping: 1.0
  gpu: 1 #set GPU to use
  wandb_project_name: Cleaning_test #project name will contain individual runs 
  wandb_entity_name: meyers_luke_lab #contains all projects in a shared workspace 
  wandb_dir_path: ./ #where to save training logs and wandb outputs
  wandb_resume: False #Can be used to link crashed runs to previous wandb runs
  checkpoint_to_load: #if resuming
data_settings:
  img_scale: 1 #scale to downsample images by
  data_paths:
    dir_img: '/home/lqmeyers/SLEAP_files/Bee_imgs/baby_bee_imgs/CVAT_sample/' #directory containing image names
    dir_mask: '/home/lqmeyers/CVAT/babyBees3perID/Label_Me_3.0/default/Masks/' #directory containing individual class maps, containing base_name of corresponding image
    dir_xml: '/home/lqmeyers/CVAT/babyBees3perID/Label_Me_3.0/default/' #dir of xml files that contain name of corresponding image and path to masks
eval_settings:

